### PR TITLE
Port to Godot 4 alpha 17

### PR DESCRIPTION
**Pull request by Sythelux**
Since it is anounced, that the beta is comming soon. I tried to port this Plugin to work with dotnet6 implementation. It still has bugs, which I'll gladly fix, maybe with some help.

But having an open pull request might help keeping track.

### CODE REVIEW

**Comment by sboron** [comment]
Hey great work. I will check it asap! Thx <3

**Comment by decryptedchaos** [comment]
If I'm being honest I'd rather see a port of this to GDscript2 

It's not likely that I'll ever target dotnet in Godoy due to it being a second class citizen.

Which doesn't appear to be changing.  To date the vast majority of training and documentation is for GDscript

**Comment by Sythelux** [comment]
> If I'm being honest I'd rather see a port of this to GDscript2
> 
> And/or GDNative
> 
> It's not likely that I'll ever target dotnet in Godot due to it being a second class citizen.
> 
> Which doesn't appear to be changing. To date the vast majority of training and documentation is for GDscript

Coming from Unity for me it is easier to Maintain a .Net Version. From Godot 4 Beta 1 owards there will probably always be a C# version along with the normal release of Godot.

I'm not the Owner of the repo, but I say feel free to make a GDNative version. If you want a GDScript based solution you can help zylann port his heightmap plugin to Godot4

**Comment by Sythelux** [comment]
I found out that @dkollmann made a fork of this, too and seems to have fixed a couple of things I haven't thought about, yet https://github.com/dkollmann/terrain-tool-godot4

Maybe we can integrate those changes as well.

**Comment by Sythelux** [comment]
fixed a few more things.

The shader is still messed up. I investigate that further. 

Also Godot 4 Beta 1 is seemingly just out. So I will try updating to that.

**Comment by Sythelux** [comment]
The Shader is compiling again.

Weirdly enough I still don't get a useful output, when I generate a new Terrain. It is just an empty Node in the Scene.

**Comment by Sythelux** [comment]
I updated it to work with the latest master Branch from Godot, which has a new FileAccess and DirAccess API.

I have to apologise I accidentially applied reformat to the var variables to be explicit types if not obvious, which is a default setting of my formatter. It doesn't hurt the compatibility, but clutters the last push a bit.

It is partially working now. It is possible to load a heightmap and it will get rendered.

Although. The rendering is glitched. I would need someone with more shader experience than me to take a look at the shader.

**Pull request merged**
