### PR TITLE
Godot 4 Stable C# Fix

### PR DESCRIPTION
**Pull request by furtherorbit**
Hi!

I've been working on porting to the addon Godot 4 stable (C#). I was able to get it to successfully build now, but I still can't get it to run/enable for the life of me. Since I wasn't making any progress on that front, I decided to make a pull request so that it could maybe at least be used as a base for further work whether or not it is merged. The enabling issue is probably something on my end tbh since it builds fine. I can't even get a brand new plugin C# to enable for whatever reason.

I've never made a pull request before, so if you want any changes, please lmk. I'm not to familiar with them. Also, if you have anything I could do to try to get it to enable to test, feel free to share that too. Most of the changes were just function call changes, and I based this off of the beta 16 PR. (ex: https://github.com/godotengine/godot/pull/66121)

### CODE REVIEW

**Comment by furtherorbit** [comment]
I have an update. I was able to get it working by removing a # in the title of my project and regenerating the csproj/sln files in my project. It seems godot or dotnet didn't like the symbols. Most features seem to work so far.

**Comment by Sythelux** [comment]
I tested it and I can confirm it working.

Although I wished @sboron would've merged my other 2 pull requests first this would've made this work easier for you.

I can't merge it though. as I'm also just contributor.

**Comment by sboron** [comment]
Thank u for fixing!

**Comment by sboron** [comment]
> I tested it and I can confirm it working.
> 
> Although I wished @sboron would've merged my other 2 pull requests first this would've made this work easier for you.
> 
> I can't merge it though. as I'm also just contributor.

Hey if u fix the merge conflicts i can merge them. Sincerely Stefan

**Comment by sboron** [comment]
Thank u for fixing!

**Pull request merged**
