### PR TITLE
csharp code convention fix

### PR DESCRIPTION
**Pull request by Sythelux**
I'm refactoring the code, to work closer to C# code conventions.

### CODE REVIEW

**Comment by Sythelux** [comment]
oh, don't pull that in just, yet please. I want to fix the MapBox bug with it too. unless you want it in and want me or us to work on the Bug together.

**Comment by Sythelux** [comment]
I didn't have time to work on this yet. I kinda suggest you if you continue working on the project then pull it in. The work itself is neat. It is more stable now, but I just hadn't had the time to polish it.

**Comment by Sythelux** [comment]
changes in here superseed #16

**Comment by spockNinja** [comment]
@Sythelux @sboron 

I would like to start contributing to this project. It looks like this PR has a lot of good work in it, and I don't want to start creating conflicts that will make it harder to merge this in later.

What all does this need in order to get merged, so I can start building on top of this work?

**Comment by Sythelux** [comment]
> 



> @Sythelux @sboron
> 
> I would like to start contributing to this project. It looks like this PR has a lot of good work in it, and I don't want to start creating conflicts that will make it harder to merge this in later.
> 
> What all does this need in order to get merged, so I can start building on top of this work?

Thank you for considering. The main issue currently is, that Stefan is indeed quite inactive on this project and yes I would love it very much, if you'd work on this branch as base as I put quite some effort into streamlining it. 

I know this is bold to this repo, but I can invite you as maintainer to my fork (https://github.com/Sythelux/TerrainPlugin) and you can help me there and we contribute to this repo together.

**Pull request closed without merging**
